# DMD训练配置文件

model:
  model_name: "NextDiT_2B_GQA_patch2_Adaln_Refiner"
  model_path: "/mnt/huggingface/Lumina-Image-2.0"
  vae_path: "/mnt/huggingface/Neta-Lumina/VAE/ae.safetensors"
  text_encoder_path: "/mnt/huggingface/Neta-Lumina/Text Encoder/gemma_2_2b_fp16.safetensors"
  init_from: "/mnt/huggingface/Neta-Lumina/Unet/neta-lumina-v1.0.safetensors"
  use_ema: false
  use_fake_model: false
  use_real_model: True

advanced:
  use_ema: false
  vae_encode_batch_size: 1

data:
  train_data_dir: "/mnt/hz_trainer/batch_output"
  val_data_dir: "/mnt/hz_trainer/batch_output_20250827_002903"
  max_train_samples: null  # 测试时限制样本数量
  max_val_samples: null

trainer:
  batch_size: 1
  learning_rate: 5e-5
  weight_decay: 0.01
  max_epochs: 100
  num_workers: 4  # 增加worker数量以提高数据加载性能
  grad_clip: 1.0
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
  precision: "bf16-mixed"
  accumulate_grad_batches: 4

generation:
  image_height: 1024
  image_width: 1024
  steps: 30
  guidance_scale: 5.0
  cfg_trunc_ratio: 1.0
  seed: null
  discrete_flow_shift: 6.0
  renorm_cfg: 1.0

k_diffusion:
  use_k_diffusion: true
  sampler: "euler_ancestral_RF"
  scheduler_func: "linear_quadratic_schedule"

output:
  output_dir: "./output" 